# CI Testing Pipeline

stages:
  - dependency
  - build

cache:
  paths:
    - .venv/
    - node_modules/

# Dependency

dependency-node:
  stage: dependency
  image: node:14
  script:
    - yarn install

# Dependency

dependency-pip:
  stage: dependency
  image: python:3.10
  script:
    - python -m pip install -r requirements.txt

# Build stage

compile-server:
  stage: build
  image: python:3.10
  script:
    # Install packages
    - python -m pip install -r requirements.txt
    # Run compile test
    - python -m py_compile server.py