stages:
  - test

compile-server:
  stage: test
  image: python:3.10
  script:
    # Install packages
    - python -m pip install -r requirements.txt
    # Run compile test
    - python -m py_compile server.py